// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

package example;
import java_cup.runtime.SymbolFactory;
import java.io.StringReader;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\2\1\22\0\1\1\1\3"+
    "\4\0\1\4\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\12\15\1\0\1\16\1\17\1\20"+
    "\1\21\2\0\22\22\1\23\7\22\1\24\1\0\1\25"+
    "\1\0\1\22\1\0\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\2\22\1\37\1\40\1\41"+
    "\1\42\1\43\1\22\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\22\1\54\1\55\1\56\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\2\21\1\22\1\23\13\21\1\2\1\21"+
    "\1\24\1\1\1\25\1\26\1\27\1\0\1\2\1\30"+
    "\1\31\1\32\7\21\1\33\11\21\1\2\1\21\1\34"+
    "\1\0\7\21\1\35\1\21\1\36\7\21\1\0\1\2"+
    "\4\21\1\37\2\21\1\40\3\21\1\41\1\42\1\43"+
    "\4\21\1\44\1\21\1\45\3\21\1\46\1\47\3\21"+
    "\1\50\1\51\1\52\1\0\1\53\1\54\12\0\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\353\0\u011a\0\57\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\57\0\57\0\u0234\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u040a\0\u0439\0\u0468\0\57\0\u0497\0\57\0\57\0\57"+
    "\0\u04c6\0\u04f5\0\57\0\57\0\57\0\u0524\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u01d6\0\u066d\0\u069c\0\u06cb"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\57\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u01d6\0\u09ea\0\u01d6\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\57\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\u01d6\0\u0c4d\0\u0c7c\0\u01d6\0\u0cab\0\u0cda\0\u0d09"+
    "\0\u01d6\0\u01d6\0\u01d6\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u01d6"+
    "\0\u0df4\0\u01d6\0\u0e23\0\u0e52\0\u0e81\0\u01d6\0\u01d6\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u01d6\0\u01d6\0\u01d6\0\u0f3d\0\u01d6\0\u01d6"+
    "\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\57";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\23\1\27\1\30"+
    "\1\23\1\31\1\32\2\23\1\33\1\23\1\34\1\35"+
    "\1\23\1\36\1\37\1\40\1\41\1\23\1\42\1\43"+
    "\2\23\1\44\1\45\1\46\60\0\2\3\45\0\1\3"+
    "\26\0\1\47\42\0\1\50\61\0\1\51\4\0\1\52"+
    "\57\0\1\16\61\0\1\53\56\0\1\54\56\0\1\55"+
    "\53\0\1\23\4\0\2\23\2\0\26\23\20\0\1\23"+
    "\4\0\2\23\2\0\20\23\1\56\4\23\1\57\20\0"+
    "\1\23\4\0\2\23\2\0\14\23\1\60\11\23\20\0"+
    "\1\23\4\0\2\23\2\0\11\23\1\61\14\23\20\0"+
    "\1\23\4\0\2\23\2\0\11\23\1\62\12\23\1\63"+
    "\1\23\20\0\1\23\4\0\2\23\2\0\1\64\25\23"+
    "\20\0\1\23\4\0\2\23\2\0\5\23\1\65\5\23"+
    "\1\66\12\23\20\0\1\23\4\0\2\23\2\0\1\67"+
    "\25\23\20\0\1\23\4\0\2\23\2\0\4\23\1\70"+
    "\21\23\20\0\1\23\4\0\2\23\2\0\21\23\1\71"+
    "\4\23\20\0\1\23\4\0\2\23\2\0\4\23\1\72"+
    "\21\23\20\0\1\23\4\0\2\23\2\0\20\23\1\73"+
    "\5\23\20\0\1\23\4\0\2\23\2\0\7\23\1\74"+
    "\6\23\1\75\7\23\4\0\2\3\12\0\1\23\4\0"+
    "\2\23\2\0\14\23\1\76\5\23\1\77\3\23\20\0"+
    "\1\23\4\0\2\23\2\0\7\23\1\100\16\23\60\0"+
    "\1\101\1\0\7\51\1\102\47\51\2\52\1\0\54\52"+
    "\15\0\1\23\4\0\2\23\2\0\16\23\1\103\7\23"+
    "\20\0\1\23\4\0\2\23\2\0\17\23\1\104\6\23"+
    "\20\0\1\23\4\0\2\23\2\0\14\23\1\105\11\23"+
    "\20\0\1\23\4\0\2\23\2\0\1\106\25\23\20\0"+
    "\1\23\4\0\2\23\2\0\17\23\1\107\6\23\20\0"+
    "\1\23\4\0\2\23\2\0\20\23\1\110\5\23\20\0"+
    "\1\23\4\0\2\23\2\0\11\23\1\111\14\23\20\0"+
    "\1\23\4\0\2\23\2\0\20\23\1\112\5\23\20\0"+
    "\1\23\4\0\2\23\2\0\10\23\1\113\15\23\20\0"+
    "\1\23\4\0\2\23\2\0\23\23\1\114\2\23\20\0"+
    "\1\23\4\0\2\23\2\0\1\23\1\115\24\23\20\0"+
    "\1\23\4\0\2\23\2\0\20\23\1\116\5\23\20\0"+
    "\1\23\4\0\2\23\2\0\1\117\25\23\20\0\1\23"+
    "\4\0\2\23\2\0\10\23\1\120\15\23\20\0\1\23"+
    "\4\0\2\23\2\0\21\23\1\121\4\23\20\0\1\23"+
    "\4\0\2\23\2\0\10\23\1\122\15\23\4\0\2\3"+
    "\12\0\1\23\4\0\2\23\2\0\22\23\1\77\3\23"+
    "\20\0\1\23\4\0\2\23\2\0\10\23\1\123\15\23"+
    "\3\0\7\51\1\124\4\51\1\125\42\51\15\0\1\23"+
    "\4\0\2\23\2\0\10\23\1\126\15\23\20\0\1\23"+
    "\4\0\2\23\2\0\20\23\1\127\5\23\20\0\1\23"+
    "\4\0\2\23\2\0\11\23\1\130\14\23\20\0\1\23"+
    "\4\0\2\23\2\0\17\23\1\131\6\23\20\0\1\23"+
    "\4\0\2\23\2\0\4\23\1\132\21\23\20\0\1\23"+
    "\4\0\2\23\2\0\4\23\1\133\21\23\20\0\1\23"+
    "\4\0\2\23\2\0\17\23\1\134\6\23\20\0\1\23"+
    "\4\0\2\23\2\0\13\23\1\135\12\23\20\0\1\23"+
    "\4\0\2\23\2\0\11\23\1\136\14\23\20\0\1\23"+
    "\4\0\2\23\2\0\21\23\1\137\4\23\20\0\1\23"+
    "\4\0\2\23\2\0\20\23\1\140\5\23\20\0\1\23"+
    "\4\0\2\23\2\0\17\23\1\141\6\23\20\0\1\23"+
    "\4\0\2\23\2\0\4\23\1\142\21\23\20\0\1\23"+
    "\4\0\2\23\2\0\3\23\1\143\22\23\20\0\1\23"+
    "\4\0\2\23\2\0\11\23\1\144\14\23\3\0\7\51"+
    "\1\124\4\51\1\0\42\51\15\0\1\23\4\0\2\23"+
    "\2\0\13\23\1\145\12\23\20\0\1\23\4\0\2\23"+
    "\2\0\4\23\1\146\21\23\20\0\1\23\4\0\2\23"+
    "\2\0\4\23\1\147\21\23\20\0\1\23\4\0\2\23"+
    "\2\0\17\23\1\150\6\23\20\0\1\23\4\0\2\23"+
    "\2\0\13\23\1\151\12\23\20\0\1\23\4\0\2\23"+
    "\2\0\4\23\1\152\21\23\20\0\1\23\4\0\2\23"+
    "\2\0\10\23\1\153\15\23\20\0\1\23\4\0\2\23"+
    "\2\0\16\23\1\154\7\23\20\0\1\23\4\0\2\23"+
    "\2\0\10\23\1\155\15\23\20\0\1\23\4\0\2\23"+
    "\2\0\4\23\1\156\21\23\20\0\1\23\4\0\2\23"+
    "\2\0\6\23\1\157\17\23\20\0\1\23\4\0\2\23"+
    "\2\0\12\23\1\160\13\23\20\0\1\23\4\0\2\23"+
    "\2\0\1\161\25\23\20\0\1\23\4\0\2\23\2\0"+
    "\3\23\1\162\22\23\20\0\1\23\4\0\2\23\2\0"+
    "\2\23\1\163\23\23\20\0\1\23\4\0\2\23\2\0"+
    "\13\23\1\164\12\23\20\0\1\23\4\0\2\23\2\0"+
    "\2\23\1\165\23\23\16\0\1\166\1\0\1\23\4\0"+
    "\2\23\2\0\26\23\20\0\1\23\4\0\2\23\2\0"+
    "\13\23\1\167\12\23\20\0\1\23\4\0\2\23\2\0"+
    "\17\23\1\170\6\23\45\0\1\171\63\0\1\172\55\0"+
    "\1\173\23\0\1\174\106\0\1\175\57\0\1\176\50\0"+
    "\1\177\61\0\1\200\63\0\1\201\47\0\1\202\60\0"+
    "\1\203\15\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4418];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\7\11\2\1\1\11\5\1\2\11"+
    "\15\1\1\11\1\1\3\11\1\0\1\1\3\11\23\1"+
    "\1\11\1\0\21\1\1\0\1\11\40\1\1\0\2\1"+
    "\12\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    SymbolFactory sf;

    public Lexer(String line, SymbolFactory sf) {
        this(new StringReader(line));
        this.sf = sf;
    }

    

// %eofval{
//     return sf.newSymbol("EOF", ParserSym.EOF);
// %eofval}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ParserSym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Illegal character: '" + yytext() + "' at line " + (yyline+1) + ", col " + yycolumn);
            }
          // fall through
          case 46: break;
          case 2:
            { 
            }
          // fall through
          case 47: break;
          case 3:
            { return sf.newSymbol ("NOT",ParserSym.NOT);
            }
          // fall through
          case 48: break;
          case 4:
            { return sf.newSymbol ("LPAREN",ParserSym.LPAREN);
            }
          // fall through
          case 49: break;
          case 5:
            { return sf.newSymbol ("RPAREN",ParserSym.RPAREN);
            }
          // fall through
          case 50: break;
          case 6:
            { return sf.newSymbol ("TIMES",ParserSym.TIMES);
            }
          // fall through
          case 51: break;
          case 7:
            { return sf.newSymbol ("PLUS",ParserSym.PLUS);
            }
          // fall through
          case 52: break;
          case 8:
            { return sf.newSymbol ("COMMA",ParserSym.COMMA);
            }
          // fall through
          case 53: break;
          case 9:
            { return sf.newSymbol ("MINUS",ParserSym.MINUS);
            }
          // fall through
          case 54: break;
          case 10:
            { return sf.newSymbol ("DOT",ParserSym.DOT);
            }
          // fall through
          case 55: break;
          case 11:
            { return sf.newSymbol ("DIVIDE",ParserSym.DIVIDE);
            }
          // fall through
          case 56: break;
          case 12:
            { return sf.newSymbol("NUMBER",ParserSym.NUM, Integer.valueOf(yytext()));
            }
          // fall through
          case 57: break;
          case 13:
            { return sf.newSymbol ("SEMI",ParserSym.SEMI);
            }
          // fall through
          case 58: break;
          case 14:
            { return sf.newSymbol ("LT",ParserSym.LT);
            }
          // fall through
          case 59: break;
          case 15:
            { return sf.newSymbol ("ASSIGN",ParserSym.ASSIGN);
            }
          // fall through
          case 60: break;
          case 16:
            { return sf.newSymbol ("GT",ParserSym.GT);
            }
          // fall through
          case 61: break;
          case 17:
            { return sf.newSymbol("ID",ParserSym.ID, yytext());
            }
          // fall through
          case 62: break;
          case 18:
            { return sf.newSymbol ("LBRACK",ParserSym.LBRACK);
            }
          // fall through
          case 63: break;
          case 19:
            { return sf.newSymbol ("RBRACK",ParserSym.RBRACK);
            }
          // fall through
          case 64: break;
          case 20:
            { return sf.newSymbol ("LBRACE",ParserSym.LBRACE);
            }
          // fall through
          case 65: break;
          case 21:
            { return sf.newSymbol ("RBRACE",ParserSym.RBRACE);
            }
          // fall through
          case 66: break;
          case 22:
            { return sf.newSymbol("NE",ParserSym.NE);
            }
          // fall through
          case 67: break;
          case 23:
            { return sf.newSymbol("AND",ParserSym.AND);
            }
          // fall through
          case 68: break;
          case 24:
            { return sf.newSymbol("LE",ParserSym.LE);
            }
          // fall through
          case 69: break;
          case 25:
            { return sf.newSymbol("EQ",ParserSym.EQ);
            }
          // fall through
          case 70: break;
          case 26:
            { return sf.newSymbol("GE",ParserSym.GE);
            }
          // fall through
          case 71: break;
          case 27:
            { return sf.newSymbol ("IF",ParserSym.IF);
            }
          // fall through
          case 72: break;
          case 28:
            { return sf.newSymbol("OR",ParserSym.OR);
            }
          // fall through
          case 73: break;
          case 29:
            { return sf.newSymbol ("INT",ParserSym.INT);
            }
          // fall through
          case 74: break;
          case 30:
            { return sf.newSymbol ("NEW",ParserSym.NEW);
            }
          // fall through
          case 75: break;
          case 31:
            { return sf.newSymbol ("ELSE",ParserSym.ELSE);
            }
          // fall through
          case 76: break;
          case 32:
            { return sf.newSymbol ("MAIN",ParserSym.MAIN);
            }
          // fall through
          case 77: break;
          case 33:
            { return sf.newSymbol ("THIS",ParserSym.THIS);
            }
          // fall through
          case 78: break;
          case 34:
            { return sf.newSymbol ("TRUE",ParserSym.TRUE);
            }
          // fall through
          case 79: break;
          case 35:
            { return sf.newSymbol ("VOID",ParserSym.VOID);
            }
          // fall through
          case 80: break;
          case 36:
            { return sf.newSymbol ("CLASS",ParserSym.CLASS);
            }
          // fall through
          case 81: break;
          case 37:
            { return sf.newSymbol ("FALSE",ParserSym.FALSE);
            }
          // fall through
          case 82: break;
          case 38:
            { return sf.newSymbol ("WHILE",ParserSym.WHILE);
            }
          // fall through
          case 83: break;
          case 39:
            { return sf.newSymbol ("STRING",ParserSym.STRING);
            }
          // fall through
          case 84: break;
          case 40:
            { return sf.newSymbol ("PUBLIC",ParserSym.PUBLIC);
            }
          // fall through
          case 85: break;
          case 41:
            { return sf.newSymbol ("RETURN",ParserSym.RETURN);
            }
          // fall through
          case 86: break;
          case 42:
            { return sf.newSymbol ("STATIC",ParserSym.STATIC);
            }
          // fall through
          case 87: break;
          case 43:
            { return sf.newSymbol ("BOOLEAN",ParserSym.BOOLEAN);
            }
          // fall through
          case 88: break;
          case 44:
            { return sf.newSymbol ("EXTENDS",ParserSym.EXTENDS);
            }
          // fall through
          case 89: break;
          case 45:
            { return sf.newSymbol ("PRINTLN",ParserSym.PRINTLN);
            }
          // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
