
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package example;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int GE = 28;
  public static final int LPAREN = 38;
  public static final int SEMI = 35;
  public static final int INT = 10;
  public static final int PRINTLN = 19;
  public static final int MINUS = 22;
  public static final int RPAREN = 39;
  public static final int STATIC = 4;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int LT = 25;
  public static final int OR = 32;
  public static final int COMMA = 36;
  public static final int CLASS = 2;
  public static final int NUM = 44;
  public static final int PLUS = 21;
  public static final int ASSIGN = 34;
  public static final int MAIN = 6;
  public static final int IF = 12;
  public static final int THIS = 15;
  public static final int ID = 45;
  public static final int DOT = 37;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 9;
  public static final int TRUE = 17;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int VOID = 5;
  public static final int EQ = 29;
  public static final int LBRACK = 42;
  public static final int TIMES = 23;
  public static final int LBRACE = 40;
  public static final int ELSE = 13;
  public static final int RBRACK = 43;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int RBRACE = 41;
  public static final int EXTENDS = 8;
  public static final int NE = 30;
  public static final int STRING = 7;
  public static final int FALSE = 18;
  public static final int GT = 26;
  public static final int LENGTH = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "STRING",
  "EXTENDS",
  "RETURN",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "THIS",
  "NEW",
  "TRUE",
  "FALSE",
  "PRINTLN",
  "LENGTH",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "GT",
  "LE",
  "GE",
  "EQ",
  "NE",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "DOT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "NUM",
  "ID"
  };
}

